version: "3.7"

services:
  datastore:
    image: google/cloud-sdk
    ports:
      - 8001:8001
    volumes:
      - ./data:/opt/data
    environment:
      - CLOUDSDK_CORE_PROJECT=test
    command: gcloud beta emulators datastore start --data-dir=/opt/data --host-port=0.0.0.0:8001

  app:
    build: .
    image: gae-py3:1.0
    ports:
      - 8080:8080
    volumes:
      - .:/app
    environment:
      # APP
      - FLASK_ENV=development
      - FLASK_APP=main.py

      # DATASTORE
      - DATASTORE_DATASET=test
      - DATASTORE_PROJECT_ID=test
      - DATASTORE_EMULATOR_HOST=datastore:8001

volumes:
  data:
  app:
